services:
  db:
    image: postgres:15-alpine
    container_name: resto_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestor_reservas
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: resto_backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      # URL estándar para Prisma 6
      DATABASE_URL: postgres://postgres:password@db:5432/gestor_reservas?schema=public
      PORT: 4000
    depends_on:
      db:
        condition: service_healthy

  # (Opcional) Visor de BD
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db